### ISSUE TITLE
Rename Protal's "name" to something else

### ISSUE THREAD

**Issue by cheapsteak** [icgc-dcc/dcc-dev#2]
options:
- slug ([web industry standard](https://en.wikipedia.org/wiki/Semantic_URL#Slug), originates from [print publishing](https://en.wikipedia.org/wiki/Slug_%28publishing%29))
- prettyUrl
- semanticUrl

To be derived from pull request title, with additional collision protection (Since PRs can have duplicate titles)

**Comment by btiernay** [comment]
Renamed `name` to `slug`. Will sluggify `slug` if present else use a sluggified `title`, else use sluggified PR `title`
